# Build Docker container

name: Container Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
#      - name: Azure login
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build image
        run: |
          docker build -f Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/github-runner:${{ github.sha }} .

      - name: Publish image
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/github-runner:${{ github.sha }}
