# Build Docker container

name: Container Build

on:
  workflow_dispatch:
    inputs:
      runner_version:
        description: 'Runner version'
        required: true
        default: '2.283.3'

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        os:
        - centos
        - ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/github-runner:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
