
name: Container Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build runner image
        run: |
          docker build -f plain/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/github-runner:latest .

      - name: Push runner image
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/github-runner:latest

      - name: Build postgres image
        run: |
          docker build -f postgres/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/github-runner-postgres:latest .

      - name: Push postgres image
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/github-runner-postgres:latest
